apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: kfp-artifact-api
  newName: jackhoman/kfp-artifact-api
  newTag: latest

resources:
- deployment.yaml
- service.yaml
- rbac.yaml

namespace: kfp-artifact-api-system