---
apiVersion: v1
kind: Service
metadata:
  name: kfp-artifact-api-node-port
  namespace: kfp-artifact-api-system
spec:
  type: NodePort
  selector:
    app: kfp-artifact-api
  ports:
    - port: 80
      targetPort: 8888
      nodePort: 30008
