---
apiVersion: v1
kind: Service
metadata:
  name: kfp-artifact-api
  namespace: system
spec:
  selector:
    app: kfp-artifact-api
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888
    name: http